//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutorial.UsuariosSR {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="USUARIOS", Namespace="http://schemas.datacontract.org/2004/07/TutorialAPI.EDM")]
    [System.SerializableAttribute()]
    public partial class USUARIOS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DATA_EXCLUSAOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DATA_NASCIMENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMAILField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SENHAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DATA_EXCLUSAO {
            get {
                return this.DATA_EXCLUSAOField;
            }
            set {
                if ((this.DATA_EXCLUSAOField.Equals(value) != true)) {
                    this.DATA_EXCLUSAOField = value;
                    this.RaisePropertyChanged("DATA_EXCLUSAO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DATA_NASCIMENTO {
            get {
                return this.DATA_NASCIMENTOField;
            }
            set {
                if ((this.DATA_NASCIMENTOField.Equals(value) != true)) {
                    this.DATA_NASCIMENTOField = value;
                    this.RaisePropertyChanged("DATA_NASCIMENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMAIL {
            get {
                return this.EMAILField;
            }
            set {
                if ((object.ReferenceEquals(this.EMAILField, value) != true)) {
                    this.EMAILField = value;
                    this.RaisePropertyChanged("EMAIL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOME {
            get {
                return this.NOMEField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMEField, value) != true)) {
                    this.NOMEField = value;
                    this.RaisePropertyChanged("NOME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SENHA {
            get {
                return this.SENHAField;
            }
            set {
                if ((object.ReferenceEquals(this.SENHAField, value) != true)) {
                    this.SENHAField = value;
                    this.RaisePropertyChanged("SENHA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsuariosSR.IUsuarios")]
    public interface IUsuarios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/DoWork", ReplyAction="http://tempuri.org/IUsuarios/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/DoWork", ReplyAction="http://tempuri.org/IUsuarios/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/CreateUser", ReplyAction="http://tempuri.org/IUsuarios/CreateUserResponse")]
        void CreateUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/CreateUser", ReplyAction="http://tempuri.org/IUsuarios/CreateUserResponse")]
        System.Threading.Tasks.Task CreateUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/ReadUser", ReplyAction="http://tempuri.org/IUsuarios/ReadUserResponse")]
        void ReadUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/ReadUser", ReplyAction="http://tempuri.org/IUsuarios/ReadUserResponse")]
        System.Threading.Tasks.Task ReadUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/UpdateUser", ReplyAction="http://tempuri.org/IUsuarios/UpdateUserResponse")]
        void UpdateUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/UpdateUser", ReplyAction="http://tempuri.org/IUsuarios/UpdateUserResponse")]
        System.Threading.Tasks.Task UpdateUserAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/DeleteUser", ReplyAction="http://tempuri.org/IUsuarios/DeleteUserResponse")]
        void DeleteUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/DeleteUser", ReplyAction="http://tempuri.org/IUsuarios/DeleteUserResponse")]
        System.Threading.Tasks.Task DeleteUserAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/AnotherTest", ReplyAction="http://tempuri.org/IUsuarios/AnotherTestResponse")]
        void AnotherTest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/AnotherTest", ReplyAction="http://tempuri.org/IUsuarios/AnotherTestResponse")]
        System.Threading.Tasks.Task AnotherTestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/GetAllUsers", ReplyAction="http://tempuri.org/IUsuarios/GetAllUsersResponse")]
        Tutorial.UsuariosSR.USUARIOS[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/GetAllUsers", ReplyAction="http://tempuri.org/IUsuarios/GetAllUsersResponse")]
        System.Threading.Tasks.Task<Tutorial.UsuariosSR.USUARIOS[]> GetAllUsersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuariosChannel : Tutorial.UsuariosSR.IUsuarios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuariosClient : System.ServiceModel.ClientBase<Tutorial.UsuariosSR.IUsuarios>, Tutorial.UsuariosSR.IUsuarios {
        
        public UsuariosClient() {
        }
        
        public UsuariosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuariosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuariosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuariosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public void CreateUser() {
            base.Channel.CreateUser();
        }
        
        public System.Threading.Tasks.Task CreateUserAsync() {
            return base.Channel.CreateUserAsync();
        }
        
        public void ReadUser() {
            base.Channel.ReadUser();
        }
        
        public System.Threading.Tasks.Task ReadUserAsync() {
            return base.Channel.ReadUserAsync();
        }
        
        public void UpdateUser(int id) {
            base.Channel.UpdateUser(id);
        }
        
        public System.Threading.Tasks.Task UpdateUserAsync(int id) {
            return base.Channel.UpdateUserAsync(id);
        }
        
        public void DeleteUser(int id) {
            base.Channel.DeleteUser(id);
        }
        
        public System.Threading.Tasks.Task DeleteUserAsync(int id) {
            return base.Channel.DeleteUserAsync(id);
        }
        
        public void AnotherTest() {
            base.Channel.AnotherTest();
        }
        
        public System.Threading.Tasks.Task AnotherTestAsync() {
            return base.Channel.AnotherTestAsync();
        }
        
        public Tutorial.UsuariosSR.USUARIOS[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<Tutorial.UsuariosSR.USUARIOS[]> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
    }
}
